import "./globals.css";

export const metadata = {
  title: "Social Downloader",
  description: "Generated by Mohit & Arjun",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
