/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6IdmDxFW10m
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Component() {
  return (
    <form className="w-full max-w-md space-y-4 bg-white">
      <div className="space-y-2">
        <Label htmlFor="name">Enter Youtube Link</Label>
        <Input id="name" placeholder="Enter your name" />
      </div>
      <Button type="submit" className="w-full">
        Submit
      </Button>
    </form>
  );
}
